### ISSUE TITLE
Some installed games are not visible

### ISSUE THREAD

**Issue by micpp42** [Ertego/gog-galaxy-itch.io#2] opened 2019-10-02 12:46 UTC
Hi,
So I'm having the issue of no games showing up. What seems to happen is when I manually run the "sync integrations" thing in the menu, it'll sync all the games into my list and I'll be able to see them... but when it finishes syncing they all disappear.
Happy to send log files etc if you can let me know what I need to send
Thanks

**Comment by lele-blue** [comment] 2019-10-02 15:00
I can't reproduce this bug so i might need log files for this.
I added a bunch of debug printouts to the integration, can you replace the itch.py file in your plugins folder with the one from this repo and attach the log (created after a restart of galaxy and reproducing the bug) to this issue?

**Comment by micpp42** [comment] 2019-10-03 10:10
Hi. I actually can't get this issue as I originally experienced to reproduce now, but instead I am getting an issue where not all of the games that I have install show up. I've attached a log for this issue... a lot of the games the log lists that it seems to be skipping over are indeed games I don't have installed, but for example one game I have installed is Minit, and the log is listing "Game 240797 (Minit) seems to be only cached, skipping.." for this one.
[plugin-itch-fd0effe6-77d9-42bc-999d-a5a5c870c2a4.log](https://github.com/Ertego/gog-galaxy-itch.io/files/3685510/plugin-itch-fd0effe6-77d9-42bc-999d-a5a5c870c2a4.log)
Not sure if that is the right log, sorry... where's it supposed to be creating them? That one was mixed in with all the other GOG logs

**Comment by lele-blue** [comment] 2019-10-03 16:41
When the integration skips a game it's because the database table for downloaded games didn't have an entry for the game.
Is your itch client able to start the game?
(It's the right log btw :) )

**Comment by lele-blue** [comment] 2019-10-03 19:57
This could also be related to [galaxy marking some games as spam](https://github.com/gogcom/galaxy-integrations-python-api/issues/72)

**Comment by micpp42** [comment] 2019-10-04 07:49
I was able to run the game through the Itch client without any issue. And as of a few minutes ago I've got the game on the Epic Store too and it seems to show up properly in my library from there... so not sure why it wouldn't be showing up from itch.

**Comment by EustaceCS** [comment] 2019-10-04 19:20
I have to mention that for me, almost all games from 18+ categories refused to appear in GOG Galaxy despite being installed and launched for a few times prior to integration activation.
Innocent Witches was the only exception - appeared in an instant.
Perky Little Things (which, I'm obliged to mention, do have a Demo and a Coming Soon page at Steam so it have to be in GOG's database somewhere) - failed to appear.
Tried random non-18+ non-popular game (it was DEFF) - appeared in an instant.

**Comment by lele-blue** [comment] 2019-10-04 23:07
@EustaceCS can you attach a log crated with the latest itch.py from this repo so i can test if the issue is on gog galaxys side or in my integration?

**Comment by lele-blue** [comment] 2019-10-04 23:09
@micpp42 in that case the problem might not be gog marking it as spam. I'll try to reproduce the issue on my side and try to find a fix :)

**Comment by EustaceCS** [comment] 2019-10-07 08:52
@Ertego , my bad, forgot about this issue.

A plenty of
2019-10-07 11:43:38,099 - root - DEBUG - Building game 379047 (Dwarf Fortress)
2019-10-07 11:43:38,099 - root - DEBUG - Game 379047 (Dwarf Fortress) seems to be only cached, skipping...
inside.
Can't imagine how and why Dwarf Fortress attempted to appear in my Itch.io library - it's not released yet (nor added to my account). Seems like it attempts to grab my Wishlist.

2019-10-07 11:42:06,999 - root - DEBUG - Building game 188955 (Godot Engine)
2019-10-07 11:42:06,999 - root - DEBUG - Game 188955 (Godot Engine) seems to be only cached, skipping...
is no less mystic case - present in my account, installed at my PC (along with a plenty of other similar entries for real games), not present in GOG Galaxy after sync.
If I remember correctly, it's okay to fetch the software - Steam integration does fetch my copy of Spriter Pro just fine.

Whole log with token scrapped:
https://drive.google.com/file/d/17GEOQJNFy53oepa1m2SK-ATdGvpYa0Ms/view?usp=sharing

**Comment by EustaceCS** [comment] 2019-10-13 11:37
After few days, all games are gone :(

**Comment by lele-blue** [comment] 2019-10-13 13:36
@EustaceCS with games vanishing over time I'm 90% sure it's due to gog marking them as spam, which is kind of inevitable at the moment due to the nature of itch being a platform with many unknown indie titles. I'll report this to the galaxy issue tracker and hope gog will resolve this soon :)

**Comment by lele-blue** [comment] 2019-10-14 12:25
@EustaceCS a gog galaxy developer replied on the issue tracker and confirmed it's on their side
Can you post a list of the missing games here so I can redirect it to the developers to unhide/match them?

**Comment by EustaceCS** [comment] 2019-10-14 15:51
@Ertego , thank you!
If the issue is not private, I'll probably add the full list there.
Here, at GITHub, - I believe, only non-adult games would do (regardless of if these were accepted at Steam or not - although Perky Little Things page is safe to mention, Steam demo doesn't include 21+ content).
Which limits me to
- GoDot Engine
- Deff
- Multi-Platform Arcade Game Designer
for games list and
- Dwarf Fortress
- The Path
for wishlist.
(since these appeared first then gone, I believe these games will be affected as installed games too)

**Comment by micpp42** [comment] 2019-10-14 22:39
So here's a list of games I've got missing on my end (i.e. installed but not showing up)

- Arc Symphony
- Depression Quest
- Escaped Chasm
- Eventual Pong
- Fortune-499
- Geek Remix Presents: Pairanormal
- Gender Prison
- Heaven Will Be Mine
- It Will Be Hard
- Keep It Together
- Kimmy
- Localhost
- Milkmaid of the Milky Way
- Minit
- Panoramical
- PUNKS - A 2064 Sidestory
- simmiland
- Social Justice Warriors
- Subserial Network
- The Tearoom
- TOUCH MELBOURNE
- VA-11 Hall-A KIDS!
- Wheels of Aurelia
- zFRAG

**Comment by lele-blue** [comment] 2019-10-16 13:24
@micpp42 @EustaceCS
I forwarded your lists to the gog galaxy devs, let's see if they unhide/match them :)

**Comment by lele-blue** [comment] 2019-10-21 13:53
There are updates to this [here](https://github.com/gogcom/galaxy-integrations-python-api/issues/72#issuecomment-544411546). Gog "froze" all unmatched itch.io games until they developed a tool that allows integrations to provide additional data for the games. Until that happens the more unknown games will unfortunately stay hidden. I'm sorry for the inconvenience and I hope gog will provide a solution to this soon :)

**Comment by micpp42** [comment] 2020-01-02 13:08
So, I've been doing a bit more playing around with this, because I noticed that newly installed games were showing up, and I realised that reinstalling games makes them show up in the list. But then they were disappearing again and I wasn't sure why.

My current working theory is that the plugin seems to be basing the appearance of games in the list on whether they're in the "downloads" window, either currently being downloaded, in the queue, or in the "recent activity" window. When you clear them out of recent activity (using the x or the "clear all" button), they'll eventually disappear from showing up in GOG.

Is it possible that the plugin, when checking whether games are downloaded, is checking the wrong thing?

**Comment by lele-blue** [comment] 2020-01-02 13:11
@micpp42 It's actually on GOGs side, they said they'd work on it eventually, but without priority
ATM there's nothing my plugin can do about it :/

**Comment by micpp42** [comment] 2020-01-02 13:20
Sorry, I don't mean to start an argument or anything but I don't think that's quite right. I had a bit of a peek at the code and it looks like you're getting the list of downloaded games from the "downloads" table in the SQLite DB. From what I can see poking around the database with a DB browser program, this table isn't actually the list of currently installed games as one would suspect, it's the list of items in the "downloads" window of the itch client. When I clear out a completed download from this window, it disappears from this table and then (when the GOG plugin refreshes) it'll disappear from the GOG library.

Try it yourself, open up the itch client and clear out a download from the "recent activity" section of the download window.

**Comment by lele-blue** [comment] 2020-01-02 14:27
Ok that's interesting and i'll take a look at this
Thanks for pointing it out :)

**Comment by micpp42** [comment] 2020-01-04 23:02
Hi, I did a bit of poking around in the code and I think I was able to fix it (changed which table it gets the downloaded games from). I'll see if I can work out how to submit the fix back to you

**Comment by micpp42** [comment] 2020-01-10 13:20
Hi, will you be putting out a new release soon (like 0.0.3 I guess) to incorporate the fixes?

**Comment by lele-blue** [comment] 2020-01-10 16:21
Yes definitely, forgot about that. I'll do it *soon* when I have a windows pc available (don't know if a release built on Linux will work on windows)

**Comment by Dr-Flay** [comment] 2020-01-13 01:58
I look forward to the next release. I wondered why I couldn't see anything.

**Comment by Bobcat90** [comment] 2020-02-15 02:52
Can't wait for the next release too! I couldn't figure out why some games showed up and others didn't (and why it changed), but micpp42 is right, the only games that show up are from the recent activity of the downloads list.

**Comment by micpp42** [comment] 2020-02-16 10:48
It's probably worth mentioning that it is possible to make use of the fixes without waiting for the next release - basically all you need to do is download the itch.py file from the repository and use it to overwrite the one in the install folder.

Might be a good idea to do that, actually - since right now it's just me who's tested it haha

**Comment by Bobcat90** [comment] 2020-02-17 03:07
Thanks for letting me know, I just tried it and it works for me! All the installed Itch games that had disappeared before show up for me now.

**Comment by lele-blue** [comment] 2020-03-20 19:04
Just pushed a new release, can someone test it to confirm everything works as it should?
https://github.com/Ertego/gog-galaxy-itch.io/releases/tag/0.0.3

**Comment by EustaceCS** [comment] 2020-03-21 11:49
@Ertego , just installed the update, relaunched Galaxy, re-connected Itch integration and... nothing changed :(
To be completely sure, reinstalled _and_ relaunched some games then restarted Galaxy.
No success.
Titles tried - present in 'add manually' menu at Galaxy - present at Steam - link to the game
DEFF - no - no - https://dinoboxstudios.itch.io/deff
Innocent Witches - yes - no - https://sad-crab.itch.io/innocent-witches

(on a side note, Milkmaid of the Milky Way did appeared so a progress has been made!)

**Comment by EustaceCS** [comment] 2020-03-22 09:08
Upd. Didn't noticed first - already-installed Maple Tea (which appeared and was runnable despite being Unknown title) disappeared >_<

**Comment by micpp42** [comment] 2020-03-22 23:49
For me, I'm not sure if this is something changed by the new update or something unrelated but at the moment it's not actually connecting for me. When I try to connect the plugin it will just end up with an "Offline, Retry" status. Retry is underlined like a link but clicking it appears to have no effect. Interestingly I can see my library of apps but can't seem to run any - a bunch that were previously showing up properly are now listed as "unknown game"

**Comment by Bobcat90** [comment] 2020-03-23 20:17
@micpp42 I'm having the same problem with the Itch plugin, but I haven't actually installed the new update yet, so I think it could be a separate issue. When I try to connect it's stuck on "connecting" for ages. I saw a solution online (https://www.gog.com/forum/general_beta_gog_galaxy_2.0/origin_integration_stuck_at_connecting) that suggested manually ending the python process for the Itch plugin (there's one for each plugin), then it says "Plugin has crashed. Retry.", but either clicking retry or disconnecting and reconnecting ends up stuck in a endless connecting stage or in "Offline Retry."

**Comment by micpp42** [comment] 2020-03-27 02:22
Looks like mine's fixed itself mysteriously now - plugin is loading up properly. Although some games that used to list names are now just showing as "unknown game", although they can still be launched (and renamed manually). As far as I can tell, installed games seem to be properly showing up now although I haven't done a detailed check to see if any are missing

**Comment by Bobcat90** [comment] 2020-03-31 15:40
Same, it looks like some other people had the same issue with various plugins (https://www.reddit.com/r/gog/comments/fp7g9j/all_my_connected_platforms_appear_offline/) and it might be fixed now. 

Btw I tried the new release and it's working fine for me so far, all installed games are appearing (but with the unknown game issue that has been reported before).

**Comment by micpp42** [comment] 2020-05-02 00:56
Hi, I've been using the new release for over a month now and all seems to be working fine. I'm figuring you can probably do a finalised release and close this issue if you want, if nobody else is having problems.

**Comment by lele-blue** [comment] 2020-05-06 15:58
Uploaded the release, should work just as the RC as i only changed the version in the manifest.

**Closed as completed by lele-blue** 2020-05-06 15:58 UTC
Labels: gog-issue
